/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_jdrd_opencv_OpenCVHelper */

#ifndef _Included_com_android_jdrd_opencv_OpenCVHelper
#define _Included_com_android_jdrd_opencv_OpenCVHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_jdrd_opencv_OpenCVHelper
 * Method:    gray
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_android_jdrd_opencv_OpenCVHelper_gray
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     com_android_jdrd_opencv_OpenCVHelper
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_android_jdrd_opencv_OpenCVHelper_init
  (JNIEnv *, jclass);

/*
 * Class:     com_android_jdrd_opencv_OpenCVHelper
 * Method:    stop
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_android_jdrd_opencv_OpenCVHelper_stop
  (JNIEnv *, jclass);

/*
 * Class:     com_android_jdrd_opencv_OpenCVHelper
 * Method:    test
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_android_jdrd_opencv_OpenCVHelper_test
  (JNIEnv *, jclass);

/*
 * Class:     com_android_jdrd_opencv_OpenCVHelper
 * Method:    get
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_android_jdrd_opencv_OpenCVHelper_get
  (JNIEnv *, jclass);

/*
 * Class:     com_android_jdrd_opencv_OpenCVHelper
 * Method:    send
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_android_jdrd_opencv_OpenCVHelper_send
  (JNIEnv *, jclass);

/*
 * Class:     com_android_jdrd_opencv_OpenCVHelper
 * Method:    getdata
 * Signature: ()I
 */
JNIEXPORT jobject JNICALL Java_com_android_jdrd_opencv_OpenCVHelper_getdata
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
