/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_jdrd_opencv_OpenCVHelper */

#ifndef _Included_com_android_jdrd_opencv_OpenCVHelper
#define _Included_com_android_jdrd_opencv_OpenCVHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_jdrd_opencv_OpenCVHelper
 * Method:    gray
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_android_jdrd_opencv_OpenCVHelper_gray
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     com_android_jdrd_opencv_OpenCVHelper
 * Method:    test
 * Signature: (I[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_android_jdrd_opencv_OpenCVHelper_test
  (JNIEnv *,jclass, jint, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
