/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_jdrd_opencv_OpenCVHelper */

#ifndef _Included_com_android_jdrd_opencv_OpenCVHelper
#define _Included_com_android_jdrd_opencv_OpenCVHelper
#ifdef __cplusplus
extern "C" {
#endif
//灰度化图片
JNIEXPORT jintArray JNICALL Java_com_android_jdrd_opencv_OpenCVHelper_gray
  (JNIEnv *, jclass, jintArray, jint, jint);

//初始化打开摄像头
JNIEXPORT jint JNICALL Java_com_android_jdrd_opencv_OpenCVHelper_init
  (JNIEnv *, jclass);

//释放关闭摄像头
JNIEXPORT jint JNICALL Java_com_android_jdrd_opencv_OpenCVHelper_stop
  (JNIEnv *, jclass);

/*
 * Class:     com_android_jdrd_opencv_OpenCVHelper
 * Method:    test
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_android_jdrd_opencv_OpenCVHelper_test
  (JNIEnv *, jclass);

/*
 * Class:     com_android_jdrd_opencv_OpenCVHelper
 * Method:    get
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_android_jdrd_opencv_OpenCVHelper_get
  (JNIEnv *, jclass);

JNIEXPORT jint JNICALL Java_com_android_jdrd_opencv_OpenCVHelper_closeget
        (JNIEnv *, jclass);

/*
 * Class:     com_android_jdrd_opencv_OpenCVHelper
 * Method:    send
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_android_jdrd_opencv_OpenCVHelper_send
  (JNIEnv *, jclass);

//获取一帧图片
JNIEXPORT jint JNICALL Java_com_android_jdrd_opencv_OpenCVHelper_getdata
  (JNIEnv *, jclass, jlong);

//向下按下
JNIEXPORT jint JNICALL Java_com_android_jdrd_opencv_OpenCVHelper_keyDownPress
  (JNIEnv *, jclass);

//向下松开
JNIEXPORT jint JNICALL Java_com_android_jdrd_opencv_OpenCVHelper_keyDownInstitute
  (JNIEnv *, jclass);

//向上按下
JNIEXPORT jint JNICALL Java_com_android_jdrd_opencv_OpenCVHelper_keyUpPress
  (JNIEnv *, jclass);

//向上松开
JNIEXPORT jint JNICALL Java_com_android_jdrd_opencv_OpenCVHelper_keyUpInstitute
  (JNIEnv *, jclass);

//向左按下
JNIEXPORT jint JNICALL Java_com_android_jdrd_opencv_OpenCVHelper_keyLeftPress
  (JNIEnv *, jclass);

//向左松开
JNIEXPORT jint JNICALL Java_com_android_jdrd_opencv_OpenCVHelper_keyLeftInstitute
  (JNIEnv *, jclass);

//向右按下
JNIEXPORT jint JNICALL Java_com_android_jdrd_opencv_OpenCVHelper_keyRightPress
  (JNIEnv *, jclass);

//向右松开
JNIEXPORT jint JNICALL Java_com_android_jdrd_opencv_OpenCVHelper_keyRightInstitute
  (JNIEnv *, jclass);
//回车
JNIEXPORT jint JNICALL Java_com_android_jdrd_opencv_OpenCVHelper_keyReturn
  (JNIEnv *, jclass);
//打开USB权限
JNIEXPORT jint JNICALL Java_com_android_jdrd_opencv_OpenCVHelper_openUsb
        (JNIEnv *,jclass,jstring, jint, jint);
//初始化鼠标按键
JNIEXPORT jint JNICALL Java_com_android_jdrd_opencv_OpenCVHelper_initMouse
        (JNIEnv *,jclass);
//发送鼠标移动
JNIEXPORT jint JNICALL Java_com_android_jdrd_opencv_OpenCVHelper_sendData
        (JNIEnv *,jclass,jint , jint ,jint);
//发送鼠标绝对值移动
JNIEXPORT jint JNICALL Java_com_android_jdrd_opencv_OpenCVHelper_sendABSData
        (JNIEnv *,jclass,jint , jint ,jint);
//发送鼠标按下松开
JNIEXPORT jint JNICALL Java_com_android_jdrd_opencv_OpenCVHelper_MousePress
        (JNIEnv *,jclass,jint);
//关闭鼠标驱动
JNIEXPORT jint JNICALL Java_com_android_jdrd_opencv_OpenCVHelper_closeMouse
        (JNIEnv *,jclass);

#ifdef __cplusplus
}
#endif
#endif
