/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_skyids_readcard_readcard_interface */
#ifndef _Included_com_skyorth_splicing_SerialPort
#define _Included_com_skyorth_splicing_SerialPort
#ifdef __cplusplus
extern "C" {
#endif
 
/* 
 * Class:     cedric_serial_SerialPort 
 * Method:    open 
 * Signature: (Ljava/lang/String;)V 
 */  
JNIEXPORT jobject JNICALL Java_com_skyworth_splicing_SerialPort_open
	(JNIEnv *env, jobject thiz, jstring path,jint baudrate);
/* 
 * Class:     cedric_serial_SerialPort 
 * Method:    close 
 * Signature: ()V 
 */  
JNIEXPORT jint JNICALL Java_com_skyworth_splicing_SerialPort_close
	(JNIEnv * env, jobject thiz);




#ifdef __cplusplus
}
#endif
#endif
